sudo: false

language: node_js

node_js:
  - "7"
  - "8"

install:
  - npm install

script:
  - npm run clean
  - npm run build:prod:config
  - npm run build:prod:webpack
  - npm test

branches:
  only:
    - master
