export default {
  TODOS_FETCH_BEGIN: 'todos/FETCH_BEGIN',
  TODOS_FETCH_SUCCESS: 'todos/FETCH_SUCCESS',
  TODOS_FETCH_FAILURE: 'todos/FETCH_FAILURE',
  TODOS_ADD: 'todos/ADD',
  TODOS_UPDATE: 'todos/UPDATE'
};
